/**
 * IMS Gen 2 — Epic 14: Mock data for Incident Response & Quarantine Management
 */

import type {
  Incident,
  QuarantineZone,
  Playbook,
  TopologyGraph,
  LateralMovementDevice,
  IncidentMetrics,
} from "./incident-types";

// ---------------------------------------------------------------------------
// Mock Incidents
// ---------------------------------------------------------------------------
export const MOCK_INCIDENTS: Incident[] = [
  {
    id: "INC-001",
    title: "Critical firmware vulnerability CVE-2026-1234",
    description:
      "A critical remote code execution vulnerability has been identified in firmware v4.0.x affecting SG-INV series inverters. Immediate isolation and patching required per NIST 800-53 IR-4.",
    severity: "Critical",
    status: "Investigating",
    category: "Security",
    affectedDevices: [
      {
        id: "DEV-101",
        name: "SG-INV-7821",
        status: "Isolated",
        location: "Shanghai HQ",
        firmwareVersion: "v4.0.3",
        isolatedAt: "2026-03-28T10:15:00Z",
        isolationPolicy: "NetworkBlock",
        riskScore: 92,
      },
      {
        id: "DEV-102",
        name: "SG-INV-7822",
        status: "Online",
        location: "Shanghai HQ",
        firmwareVersion: "v4.0.3",
        riskScore: 88,
      },
      {
        id: "DEV-103",
        name: "SG-INV-4901",
        status: "Online",
        location: "Denver DC",
        firmwareVersion: "v4.0.2",
        riskScore: 76,
      },
      {
        id: "DEV-104",
        name: "SG-INV-4892",
        status: "Offline",
        location: "Denver DC",
        firmwareVersion: "v4.0.3",
        riskScore: 65,
      },
      {
        id: "DEV-105",
        name: "SG-INV-3310",
        status: "Online",
        location: "Munich Office",
        firmwareVersion: "v4.0.1",
        riskScore: 71,
      },
    ],
    affectedDeviceCount: 5,
    originDeviceId: "DEV-101",
    assignedTo: "USR-001",
    assignedToName: "Sarah Chen",
    reportedBy: "USR-002",
    reportedByName: "Raj Patel",
    playbookId: "PB-001",
    playbookProgress: {
      playbookId: "PB-001",
      playbookName: "Critical Firmware Vulnerability Response",
      totalSteps: 7,
      completedSteps: 3,
      steps: [
        {
          stepNumber: 1,
          title: "Identify affected devices",
          description: "Query inventory for all devices running vulnerable firmware version.",
          actionType: "manual",
          isCompleted: true,
          completedBy: "USR-001",
          completedByName: "Sarah Chen",
          completedAt: "2026-03-28T09:30:00Z",
        },
        {
          stepNumber: 2,
          title: "Isolate origin device",
          description: "Immediately isolate the device where the vulnerability was first detected.",
          actionType: "automated",
          automatedAction: "isolate_device",
          isCompleted: true,
          completedBy: "USR-001",
          completedByName: "Sarah Chen",
          completedAt: "2026-03-28T09:45:00Z",
        },
        {
          stepNumber: 3,
          title: "Notify security team",
          description: "Send urgent notification to the security response team.",
          actionType: "automated",
          automatedAction: "notify_team",
          isCompleted: true,
          completedBy: "USR-001",
          completedByName: "Sarah Chen",
          completedAt: "2026-03-28T10:00:00Z",
        },
        {
          stepNumber: 4,
          title: "Assess lateral movement risk",
          description: "Review network topology to identify potential lateral movement paths.",
          actionType: "manual",
          isCompleted: false,
        },
        {
          stepNumber: 5,
          title: "Create quarantine zone",
          description: "Establish quarantine zone around affected area if lateral risk is high.",
          actionType: "automated",
          automatedAction: "create_quarantine",
          isCompleted: false,
        },
        {
          stepNumber: 6,
          title: "Deploy firmware patch",
          description: "Push patched firmware to all affected devices.",
          actionType: "manual",
          isCompleted: false,
        },
        {
          stepNumber: 7,
          title: "Verify remediation",
          description: "Confirm all devices are patched and release from isolation.",
          actionType: "manual",
          isCompleted: false,
        },
      ],
    },
    timelineEvents: [
      {
        timestamp: "2026-03-28T09:00:00Z",
        action: "created",
        performedBy: "USR-002",
        performedByName: "Raj Patel",
        note: "CVE-2026-1234 detected by automated scan",
      },
      {
        timestamp: "2026-03-28T09:15:00Z",
        action: "assigned",
        performedBy: "USR-002",
        performedByName: "Raj Patel",
        note: "Assigned to Sarah Chen for investigation",
      },
      {
        timestamp: "2026-03-28T09:20:00Z",
        action: "status_changed",
        performedBy: "USR-001",
        performedByName: "Sarah Chen",
        fromStatus: "Open",
        toStatus: "Investigating",
        note: "Beginning investigation of affected devices",
      },
      {
        timestamp: "2026-03-28T10:15:00Z",
        action: "device_isolated",
        performedBy: "USR-001",
        performedByName: "Sarah Chen",
        deviceId: "DEV-101",
        deviceName: "SG-INV-7821",
        note: "Isolated origin device — NetworkBlock policy applied",
      },
      {
        timestamp: "2026-03-28T10:30:00Z",
        action: "playbook_started",
        performedBy: "USR-001",
        performedByName: "Sarah Chen",
        note: "Started playbook: Critical Firmware Vulnerability Response",
      },
    ],
    createdAt: "2026-03-28T09:00:00Z",
    updatedAt: "2026-03-28T10:30:00Z",
  },
  {
    id: "INC-002",
    title: "Network connectivity loss — Singapore Lab",
    description:
      "Multiple devices in Singapore Lab have gone offline simultaneously, indicating possible network infrastructure failure or targeted attack.",
    severity: "High",
    status: "Contained",
    category: "Network",
    affectedDevices: [
      {
        id: "DEV-201",
        name: "SG-LAB-1001",
        status: "Isolated",
        location: "Singapore Lab",
        firmwareVersion: "v3.9.8",
        isolatedAt: "2026-03-27T14:00:00Z",
        isolationPolicy: "ReadOnly",
        riskScore: 58,
      },
      {
        id: "DEV-202",
        name: "SG-LAB-1002",
        status: "Isolated",
        location: "Singapore Lab",
        firmwareVersion: "v3.9.8",
        isolatedAt: "2026-03-27T14:00:00Z",
        isolationPolicy: "ReadOnly",
        riskScore: 52,
      },
      {
        id: "DEV-203",
        name: "SG-LAB-1003",
        status: "Offline",
        location: "Singapore Lab",
        firmwareVersion: "v3.9.7",
        riskScore: 45,
      },
    ],
    affectedDeviceCount: 3,
    originDeviceId: "DEV-201",
    assignedTo: "USR-003",
    assignedToName: "Mike Johnson",
    reportedBy: "USR-001",
    reportedByName: "Sarah Chen",
    quarantineZoneId: "QZ-001",
    timelineEvents: [
      {
        timestamp: "2026-03-27T13:00:00Z",
        action: "created",
        performedBy: "USR-001",
        performedByName: "Sarah Chen",
        note: "Multiple devices went offline in Singapore Lab",
      },
      {
        timestamp: "2026-03-27T13:30:00Z",
        action: "status_changed",
        performedBy: "USR-003",
        performedByName: "Mike Johnson",
        fromStatus: "Open",
        toStatus: "Investigating",
      },
      {
        timestamp: "2026-03-27T14:00:00Z",
        action: "quarantine_applied",
        performedBy: "USR-001",
        performedByName: "Sarah Chen",
        note: "Quarantine zone created for Singapore Lab area",
      },
      {
        timestamp: "2026-03-27T15:00:00Z",
        action: "status_changed",
        performedBy: "USR-003",
        performedByName: "Mike Johnson",
        fromStatus: "Investigating",
        toStatus: "Contained",
        note: "Network issue isolated to faulty switch in rack 3B",
      },
    ],
    containedAt: "2026-03-27T15:00:00Z",
    createdAt: "2026-03-27T13:00:00Z",
    updatedAt: "2026-03-27T15:00:00Z",
  },
  {
    id: "INC-003",
    title: "Hardware failure — Denver DC inverter overheating",
    description:
      "Inverter SG-INV-5500 reporting abnormal temperature readings. Adjacent devices showing elevated thermal signatures.",
    severity: "Medium",
    status: "Open",
    category: "Hardware",
    affectedDevices: [
      {
        id: "DEV-301",
        name: "SG-INV-5500",
        status: "Online",
        location: "Denver DC",
        firmwareVersion: "v4.1.2",
        riskScore: 62,
      },
      {
        id: "DEV-302",
        name: "SG-INV-5501",
        status: "Online",
        location: "Denver DC",
        firmwareVersion: "v4.1.2",
        riskScore: 38,
      },
    ],
    affectedDeviceCount: 2,
    originDeviceId: "DEV-301",
    assignedTo: "USR-004",
    assignedToName: "Ana Martinez",
    reportedBy: "USR-003",
    reportedByName: "Mike Johnson",
    timelineEvents: [
      {
        timestamp: "2026-03-29T08:00:00Z",
        action: "created",
        performedBy: "USR-003",
        performedByName: "Mike Johnson",
        note: "Temperature alert triggered for SG-INV-5500",
      },
    ],
    createdAt: "2026-03-29T08:00:00Z",
    updatedAt: "2026-03-29T08:00:00Z",
  },
  {
    id: "INC-004",
    title: "Firmware deployment rollback — Sao Paulo Site",
    description:
      "Firmware v4.2.0-beta deployed to Sao Paulo Site caused intermittent power output fluctuations. Rollback to v4.1.2 initiated.",
    severity: "High",
    status: "Resolved",
    category: "Firmware",
    affectedDevices: [
      {
        id: "DEV-401",
        name: "SG-SP-2001",
        status: "Online",
        location: "Sao Paulo Site",
        firmwareVersion: "v4.1.2",
        riskScore: 25,
      },
      {
        id: "DEV-402",
        name: "SG-SP-2002",
        status: "Online",
        location: "Sao Paulo Site",
        firmwareVersion: "v4.1.2",
        riskScore: 22,
      },
      {
        id: "DEV-403",
        name: "SG-SP-2003",
        status: "Online",
        location: "Sao Paulo Site",
        firmwareVersion: "v4.1.2",
        riskScore: 20,
      },
      {
        id: "DEV-404",
        name: "SG-SP-2004",
        status: "Online",
        location: "Sao Paulo Site",
        firmwareVersion: "v4.1.2",
        riskScore: 18,
      },
    ],
    affectedDeviceCount: 4,
    originDeviceId: "DEV-401",
    assignedTo: "USR-002",
    assignedToName: "Raj Patel",
    reportedBy: "USR-004",
    reportedByName: "Ana Martinez",
    timelineEvents: [
      {
        timestamp: "2026-03-25T10:00:00Z",
        action: "created",
        performedBy: "USR-004",
        performedByName: "Ana Martinez",
      },
      {
        timestamp: "2026-03-25T10:30:00Z",
        action: "status_changed",
        performedBy: "USR-002",
        performedByName: "Raj Patel",
        fromStatus: "Open",
        toStatus: "Investigating",
      },
      {
        timestamp: "2026-03-25T14:00:00Z",
        action: "status_changed",
        performedBy: "USR-002",
        performedByName: "Raj Patel",
        fromStatus: "Investigating",
        toStatus: "Contained",
        note: "Firmware rollback initiated",
      },
      {
        timestamp: "2026-03-26T09:00:00Z",
        action: "status_changed",
        performedBy: "USR-002",
        performedByName: "Raj Patel",
        fromStatus: "Contained",
        toStatus: "Resolved",
        note: "All devices rolled back to v4.1.2 successfully. Power output stable.",
      },
    ],
    containedAt: "2026-03-25T14:00:00Z",
    resolvedAt: "2026-03-26T09:00:00Z",
    createdAt: "2026-03-25T10:00:00Z",
    updatedAt: "2026-03-26T09:00:00Z",
  },
  {
    id: "INC-005",
    title: "Environmental alert — Munich Office humidity spike",
    description:
      "Humidity sensors in Munich Office server room reporting levels above safe threshold (>80%). Risk of condensation damage to devices.",
    severity: "Low",
    status: "Open",
    category: "Environmental",
    affectedDevices: [
      {
        id: "DEV-501",
        name: "SG-MUN-3001",
        status: "Online",
        location: "Munich Office",
        firmwareVersion: "v4.1.1",
        riskScore: 30,
      },
    ],
    affectedDeviceCount: 1,
    originDeviceId: "DEV-501",
    assignedTo: "USR-004",
    assignedToName: "Ana Martinez",
    reportedBy: "USR-002",
    reportedByName: "Raj Patel",
    timelineEvents: [
      {
        timestamp: "2026-03-29T06:00:00Z",
        action: "created",
        performedBy: "USR-002",
        performedByName: "Raj Patel",
        note: "Automated humidity alert from Munich Office",
      },
    ],
    createdAt: "2026-03-29T06:00:00Z",
    updatedAt: "2026-03-29T06:00:00Z",
  },
];

// ---------------------------------------------------------------------------
// Mock Quarantine Zones
// ---------------------------------------------------------------------------
export const MOCK_QUARANTINE_ZONES: QuarantineZone[] = [
  {
    id: "QZ-001",
    name: "Singapore Lab Quarantine",
    description:
      "Emergency quarantine zone established for Singapore Lab due to network connectivity loss affecting multiple devices.",
    status: "Active",
    isolatedDeviceIds: ["DEV-201", "DEV-202"],
    isolatedDeviceCount: 2,
    incidentId: "INC-002",
    incidentTitle: "Network connectivity loss — Singapore Lab",
    centerLat: 1.3521,
    centerLng: 103.8198,
    radiusKm: 0.5,
    isolationPolicy: "ReadOnly",
    createdBy: "USR-001",
    createdByName: "Sarah Chen",
    createdAt: "2026-03-27T14:00:00Z",
  },
  {
    id: "QZ-002",
    name: "Shanghai West Perimeter",
    description:
      "Precautionary quarantine for the western section of Shanghai HQ during firmware vulnerability investigation.",
    status: "Active",
    isolatedDeviceIds: ["DEV-101"],
    isolatedDeviceCount: 1,
    incidentId: "INC-001",
    incidentTitle: "Critical firmware vulnerability CVE-2026-1234",
    centerLat: 31.2304,
    centerLng: 121.4737,
    radiusKm: 1.2,
    isolationPolicy: "NetworkBlock",
    createdBy: "USR-001",
    createdByName: "Sarah Chen",
    createdAt: "2026-03-28T11:00:00Z",
  },
  {
    id: "QZ-003",
    name: "Denver DC Zone A",
    description: "Temporary quarantine lifted after hardware issue was resolved.",
    status: "Lifted",
    isolatedDeviceIds: [],
    isolatedDeviceCount: 0,
    incidentId: "INC-003",
    incidentTitle: "Hardware failure — Denver DC inverter overheating",
    centerLat: 39.7392,
    centerLng: -104.9903,
    radiusKm: 0.3,
    isolationPolicy: "FirmwareLock",
    createdBy: "USR-003",
    createdByName: "Mike Johnson",
    createdAt: "2026-03-20T10:00:00Z",
    liftedAt: "2026-03-22T16:00:00Z",
    liftedBy: "USR-003",
    liftedByName: "Mike Johnson",
    liftReason: "Hardware issue resolved, replacement switch installed.",
  },
];

// ---------------------------------------------------------------------------
// Mock Playbooks
// ---------------------------------------------------------------------------
export const MOCK_PLAYBOOKS: Playbook[] = [
  {
    id: "PB-001",
    name: "Critical Firmware Vulnerability Response",
    description:
      "Standard operating procedure for responding to critical firmware vulnerabilities affecting fleet devices. Includes isolation, assessment, patching, and verification steps.",
    category: "Security",
    steps: [
      {
        stepNumber: 1,
        title: "Identify affected devices",
        description: "Query inventory for all devices running vulnerable firmware version.",
        actionType: "manual",
        isCompleted: false,
      },
      {
        stepNumber: 2,
        title: "Isolate origin device",
        description: "Immediately isolate the device where the vulnerability was first detected.",
        actionType: "automated",
        automatedAction: "isolate_device",
        isCompleted: false,
      },
      {
        stepNumber: 3,
        title: "Notify security team",
        description: "Send urgent notification to the security response team.",
        actionType: "automated",
        automatedAction: "notify_team",
        isCompleted: false,
      },
      {
        stepNumber: 4,
        title: "Assess lateral movement risk",
        description: "Review network topology to identify potential lateral movement paths.",
        actionType: "manual",
        isCompleted: false,
      },
      {
        stepNumber: 5,
        title: "Create quarantine zone",
        description: "Establish quarantine zone around affected area if lateral risk is high.",
        actionType: "automated",
        automatedAction: "create_quarantine",
        isCompleted: false,
      },
      {
        stepNumber: 6,
        title: "Deploy firmware patch",
        description: "Push patched firmware to all affected devices.",
        actionType: "manual",
        isCompleted: false,
      },
      {
        stepNumber: 7,
        title: "Verify remediation",
        description: "Confirm all devices are patched and release from isolation.",
        actionType: "manual",
        isCompleted: false,
      },
    ],
    stepCount: 7,
    estimatedDurationMinutes: 240,
    severity: "Critical",
    status: "Active",
    createdBy: "USR-001",
    createdByName: "Sarah Chen",
    createdAt: "2026-01-15T10:00:00Z",
    updatedAt: "2026-02-20T14:00:00Z",
  },
  {
    id: "PB-002",
    name: "Network Outage Recovery",
    description:
      "Procedure for handling network outages affecting device connectivity. Covers diagnosis, isolation, failover, and recovery verification.",
    category: "Network",
    steps: [
      {
        stepNumber: 1,
        title: "Confirm outage scope",
        description: "Determine which devices and regions are affected by the outage.",
        actionType: "manual",
        isCompleted: false,
      },
      {
        stepNumber: 2,
        title: "Notify operations team",
        description: "Alert the operations team about the outage.",
        actionType: "automated",
        automatedAction: "notify_team",
        isCompleted: false,
      },
      {
        stepNumber: 3,
        title: "Isolate affected segment",
        description: "Isolate the affected network segment to prevent cascade failures.",
        actionType: "manual",
        isCompleted: false,
      },
      {
        stepNumber: 4,
        title: "Activate failover",
        description: "Switch to backup network path if available.",
        actionType: "manual",
        isCompleted: false,
      },
      {
        stepNumber: 5,
        title: "Verify connectivity restored",
        description: "Confirm all devices are back online and communicating.",
        actionType: "manual",
        isCompleted: false,
      },
    ],
    stepCount: 5,
    estimatedDurationMinutes: 120,
    severity: "High",
    status: "Active",
    createdBy: "USR-002",
    createdByName: "Raj Patel",
    createdAt: "2026-02-01T09:00:00Z",
    updatedAt: "2026-03-10T11:00:00Z",
  },
  {
    id: "PB-003",
    name: "Hardware Failure Triage",
    description:
      "Step-by-step procedure for triaging hardware failures including thermal events, power anomalies, and physical damage assessment.",
    category: "Hardware",
    steps: [
      {
        stepNumber: 1,
        title: "Gather telemetry data",
        description: "Pull recent telemetry readings for the affected device(s).",
        actionType: "manual",
        isCompleted: false,
      },
      {
        stepNumber: 2,
        title: "Assess failure severity",
        description: "Determine if the failure is critical, degraded, or minor.",
        actionType: "manual",
        isCompleted: false,
      },
      {
        stepNumber: 3,
        title: "Lock firmware",
        description: "Prevent firmware changes on the affected device during investigation.",
        actionType: "automated",
        automatedAction: "lock_firmware",
        isCompleted: false,
      },
      {
        stepNumber: 4,
        title: "Schedule site visit",
        description: "Create service order for physical inspection if needed.",
        actionType: "manual",
        isCompleted: false,
      },
    ],
    stepCount: 4,
    estimatedDurationMinutes: 90,
    severity: "Medium",
    status: "Active",
    createdBy: "USR-003",
    createdByName: "Mike Johnson",
    createdAt: "2026-02-15T08:00:00Z",
    updatedAt: "2026-02-15T08:00:00Z",
  },
  {
    id: "PB-004",
    name: "Environmental Hazard Response",
    description:
      "Response procedure for environmental hazards (temperature, humidity, flooding) that may affect device operations.",
    category: "Environmental",
    steps: [
      {
        stepNumber: 1,
        title: "Verify sensor readings",
        description: "Cross-reference environmental sensor data with device telemetry.",
        actionType: "manual",
        isCompleted: false,
      },
      {
        stepNumber: 2,
        title: "Notify facility management",
        description: "Alert facility management team about the environmental issue.",
        actionType: "automated",
        automatedAction: "notify_team",
        isCompleted: false,
      },
      {
        stepNumber: 3,
        title: "Assess device risk",
        description: "Determine which devices are at risk from the environmental condition.",
        actionType: "manual",
        isCompleted: false,
      },
    ],
    stepCount: 3,
    estimatedDurationMinutes: 60,
    severity: "Low",
    status: "Draft",
    createdBy: "USR-004",
    createdByName: "Ana Martinez",
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-03-01T10:00:00Z",
  },
];

// ---------------------------------------------------------------------------
// Mock Topology Graph (for INC-001)
// ---------------------------------------------------------------------------
export const MOCK_TOPOLOGY: TopologyGraph = {
  nodes: [
    {
      id: "DEV-101",
      deviceName: "SG-INV-7821",
      status: "Isolated",
      riskScore: 92,
      lat: 31.23,
      lng: 121.473,
      firmwareVersion: "v4.0.3",
      location: "Shanghai HQ",
      isOrigin: true,
      isIsolated: true,
    },
    {
      id: "DEV-102",
      deviceName: "SG-INV-7822",
      status: "Online",
      riskScore: 88,
      lat: 31.231,
      lng: 121.474,
      firmwareVersion: "v4.0.3",
      location: "Shanghai HQ",
      isOrigin: false,
      isIsolated: false,
    },
    {
      id: "DEV-103",
      deviceName: "SG-INV-4901",
      status: "Online",
      riskScore: 76,
      lat: 39.739,
      lng: -104.99,
      firmwareVersion: "v4.0.2",
      location: "Denver DC",
      isOrigin: false,
      isIsolated: false,
    },
    {
      id: "DEV-104",
      deviceName: "SG-INV-4892",
      status: "Offline",
      riskScore: 65,
      lat: 39.74,
      lng: -104.991,
      firmwareVersion: "v4.0.3",
      location: "Denver DC",
      isOrigin: false,
      isIsolated: false,
    },
    {
      id: "DEV-105",
      deviceName: "SG-INV-3310",
      status: "Online",
      riskScore: 71,
      lat: 48.135,
      lng: 11.582,
      firmwareVersion: "v4.0.1",
      location: "Munich Office",
      isOrigin: false,
      isIsolated: false,
    },
    {
      id: "DEV-106",
      deviceName: "SG-INV-7823",
      status: "Online",
      riskScore: 55,
      lat: 31.232,
      lng: 121.475,
      firmwareVersion: "v4.1.2",
      location: "Shanghai HQ",
      isOrigin: false,
      isIsolated: false,
    },
    {
      id: "DEV-107",
      deviceName: "SG-INV-4903",
      status: "Online",
      riskScore: 42,
      lat: 39.738,
      lng: -104.989,
      firmwareVersion: "v4.1.2",
      location: "Denver DC",
      isOrigin: false,
      isIsolated: false,
    },
    {
      id: "DEV-108",
      deviceName: "SG-INV-3311",
      status: "Online",
      riskScore: 38,
      lat: 48.136,
      lng: 11.583,
      firmwareVersion: "v4.0.1",
      location: "Munich Office",
      isOrigin: false,
      isIsolated: false,
    },
  ],
  edges: [
    { source: "DEV-101", target: "DEV-102", relationshipType: "same_firmware", weight: 0.95 },
    { source: "DEV-101", target: "DEV-106", relationshipType: "same_location", weight: 0.8 },
    { source: "DEV-102", target: "DEV-106", relationshipType: "same_location", weight: 0.8 },
    { source: "DEV-101", target: "DEV-104", relationshipType: "same_firmware", weight: 0.7 },
    { source: "DEV-103", target: "DEV-104", relationshipType: "same_location", weight: 0.85 },
    { source: "DEV-103", target: "DEV-107", relationshipType: "same_location", weight: 0.75 },
    { source: "DEV-104", target: "DEV-107", relationshipType: "same_location", weight: 0.75 },
    { source: "DEV-105", target: "DEV-108", relationshipType: "same_location", weight: 0.9 },
    { source: "DEV-105", target: "DEV-108", relationshipType: "same_firmware", weight: 0.85 },
    { source: "DEV-102", target: "DEV-104", relationshipType: "same_firmware", weight: 0.7 },
    { source: "DEV-103", target: "DEV-105", relationshipType: "same_customer", weight: 0.5 },
    { source: "DEV-106", target: "DEV-107", relationshipType: "geographic_proximity", weight: 0.3 },
  ],
};

// ---------------------------------------------------------------------------
// Mock Lateral Movement Analysis (for DEV-101)
// ---------------------------------------------------------------------------
export const MOCK_LATERAL_MOVEMENT: LateralMovementDevice[] = [
  {
    deviceId: "DEV-102",
    deviceName: "SG-INV-7822",
    probability: 94,
    primaryRiskFactor: "Same firmware v4.0.3 + same location",
    status: "Online",
  },
  {
    deviceId: "DEV-104",
    deviceName: "SG-INV-4892",
    probability: 78,
    primaryRiskFactor: "Same firmware v4.0.3",
    status: "Offline",
  },
  {
    deviceId: "DEV-106",
    deviceName: "SG-INV-7823",
    probability: 65,
    primaryRiskFactor: "Same location (Shanghai HQ)",
    status: "Online",
  },
  {
    deviceId: "DEV-103",
    deviceName: "SG-INV-4901",
    probability: 52,
    primaryRiskFactor: "Similar firmware v4.0.x family",
    status: "Online",
  },
  {
    deviceId: "DEV-105",
    deviceName: "SG-INV-3310",
    probability: 38,
    primaryRiskFactor: "Similar firmware v4.0.x family",
    status: "Online",
  },
  {
    deviceId: "DEV-108",
    deviceName: "SG-INV-3311",
    probability: 25,
    primaryRiskFactor: "Same customer network segment",
    status: "Online",
  },
  {
    deviceId: "DEV-107",
    deviceName: "SG-INV-4903",
    probability: 15,
    primaryRiskFactor: "Geographic proximity only",
    status: "Online",
  },
];

// ---------------------------------------------------------------------------
// Mock Metrics (Story 14.6)
// ---------------------------------------------------------------------------
export const MOCK_INCIDENT_METRICS: IncidentMetrics = {
  openIncidents: 3,
  isolatedDevices: 3,
  activeQuarantineZones: 2,
  hasCritical: true,
  meanTimeToContainHours: 4.2,
  meanTimeToResolveHours: 18.5,
  mttcTrend: -12,
  mttrTrend: -8,
  bySeverity: [
    { severity: "Critical", count: 1 },
    { severity: "High", count: 2 },
    { severity: "Medium", count: 1 },
    { severity: "Low", count: 1 },
  ],
};

// ---------------------------------------------------------------------------
// Mock team members for assignment
// ---------------------------------------------------------------------------
export const MOCK_TEAM_MEMBERS = [
  { id: "USR-001", name: "Sarah Chen", role: "Admin" },
  { id: "USR-002", name: "Raj Patel", role: "Manager" },
  { id: "USR-003", name: "Mike Johnson", role: "Manager" },
  { id: "USR-004", name: "Ana Martinez", role: "Technician" },
  { id: "USR-005", name: "David Kim", role: "Technician" },
];
