########### browser settings ###########
browser.headless=true
browser.width=1620
browser.height=1080
browser.slowmo=100
browser.headless.args=--headless=new
browser.ignore.args=--headless
browser.fullscreen=--start-maximized
browser.fullscreen.enabled=true