// =============================================================================
// Customer & Site Mock Data — Story #389
// 5 customers, 10 sites, 18 deployment records
// =============================================================================

import type { Customer } from "../types";
import type { Site, SiteDeployment } from "../types/customer-site";

// ---------------------------------------------------------------------------
// Customers
// ---------------------------------------------------------------------------

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: "cust-001",
    name: "Shanghai Power Systems",
    code: "SPS",
    contactEmail: "wang.li@shanghaips.com",
    contactPhone: "+86-21-5555-0100",
    address: "88 Century Avenue, Pudong, Shanghai, China",
    deviceCount: 45,
    activeServiceOrders: 2,
    complianceScore: 94,
    createdAt: "2025-03-15T08:00:00Z",
  },
  {
    id: "cust-002",
    name: "Sydney Solar Farms",
    code: "SSF",
    contactEmail: "j.thompson@sydneysolar.com.au",
    contactPhone: "+61-2-9555-0200",
    address: "120 George Street, Sydney, NSW 2000, Australia",
    deviceCount: 32,
    activeServiceOrders: 1,
    complianceScore: 97,
    createdAt: "2025-04-10T10:00:00Z",
  },
  {
    id: "cust-003",
    name: "Brisbane Energy Grid",
    code: "BEG",
    contactEmail: "m.nguyen@brisbanegrid.com.au",
    contactPhone: "+61-7-3555-0300",
    address: "45 Eagle Street, Brisbane, QLD 4000, Australia",
    deviceCount: 28,
    activeServiceOrders: 0,
    complianceScore: 91,
    createdAt: "2025-06-01T09:00:00Z",
  },
  {
    id: "cust-004",
    name: "Munich Industrial Solutions",
    code: "MIS",
    contactEmail: "h.mueller@munichis.de",
    contactPhone: "+49-89-5555-0400",
    address: "Leopoldstraße 42, 80802 München, Germany",
    deviceCount: 18,
    activeServiceOrders: 3,
    complianceScore: 88,
    createdAt: "2025-07-20T11:00:00Z",
  },
  {
    id: "cust-005",
    name: "Texas Renewables Corp",
    code: "TRC",
    contactEmail: "b.johnson@texasrenew.com",
    contactPhone: "+1-512-555-0500",
    address: "1200 Congress Avenue, Austin, TX 78701, USA",
    deviceCount: 55,
    activeServiceOrders: 1,
    complianceScore: 95,
    createdAt: "2025-08-05T08:00:00Z",
  },
];

// ---------------------------------------------------------------------------
// Sites
// ---------------------------------------------------------------------------

export const MOCK_SITES: Site[] = [
  // Shanghai Power Systems
  {
    id: "site-001",
    customerId: "cust-001",
    name: "Shanghai HQ Plant",
    location: "Pudong, Shanghai",
    coordinates: { lat: 31.2304, lng: 121.4737 },
    deviceCount: 30,
    currentFirmwareVersionId: "fwv-103",
    currentFirmwareVersion: "v1.2.0",
    currentFirmwareFamilyName: "INV-3200 Power Controller",
    lastDeploymentAt: "2025-11-01T08:00:00Z",
    status: "active",
  },
  {
    id: "site-002",
    customerId: "cust-001",
    name: "Nanjing Distribution Center",
    location: "Nanjing, Jiangsu",
    coordinates: { lat: 32.0603, lng: 118.7969 },
    deviceCount: 15,
    currentFirmwareVersionId: "fwv-101",
    currentFirmwareVersion: "v1.0.0",
    currentFirmwareFamilyName: "INV-3200 Power Controller",
    lastDeploymentAt: "2025-08-20T10:00:00Z",
    status: "active",
  },
  // Sydney Solar Farms
  {
    id: "site-003",
    customerId: "cust-002",
    name: "Western Sydney Solar Array",
    location: "Penrith, NSW",
    coordinates: { lat: -33.7506, lng: 150.6944 },
    deviceCount: 20,
    currentFirmwareVersionId: "fwv-202",
    currentFirmwareVersion: "v2.1.0",
    currentFirmwareFamilyName: "INV-5000 Gateway",
    lastDeploymentAt: "2026-01-10T08:00:00Z",
    status: "active",
  },
  {
    id: "site-004",
    customerId: "cust-002",
    name: "Hunter Valley Plant",
    location: "Cessnock, NSW",
    coordinates: { lat: -32.8321, lng: 151.3561 },
    deviceCount: 12,
    currentFirmwareVersionId: "fwv-103",
    currentFirmwareVersion: "v1.2.0",
    currentFirmwareFamilyName: "INV-3200 Power Controller",
    lastDeploymentAt: "2025-11-01T08:00:00Z",
    status: "active",
  },
  // Brisbane Energy Grid
  {
    id: "site-005",
    customerId: "cust-003",
    name: "Brisbane Central Substation",
    location: "Fortitude Valley, QLD",
    coordinates: { lat: -27.4558, lng: 153.0351 },
    deviceCount: 20,
    currentFirmwareVersionId: "fwv-301",
    currentFirmwareVersion: "v3.0.0",
    currentFirmwareFamilyName: "INV-4000 Inverter Controller",
    lastDeploymentAt: "2026-01-20T10:00:00Z",
    status: "active",
  },
  {
    id: "site-006",
    customerId: "cust-003",
    name: "Gold Coast Monitoring Hub",
    location: "Southport, QLD",
    coordinates: { lat: -27.9659, lng: 153.3981 },
    deviceCount: 8,
    currentFirmwareVersionId: "fwv-202",
    currentFirmwareVersion: "v2.1.0",
    currentFirmwareFamilyName: "INV-5000 Gateway",
    lastDeploymentAt: "2026-01-10T08:00:00Z",
    status: "maintenance",
  },
  // Munich Industrial Solutions
  {
    id: "site-007",
    customerId: "cust-004",
    name: "Munich Factory Floor",
    location: "Schwabing, Munich",
    coordinates: { lat: 48.1713, lng: 11.5768 },
    deviceCount: 10,
    currentFirmwareVersionId: "fwv-103",
    currentFirmwareVersion: "v1.2.0",
    currentFirmwareFamilyName: "INV-3200 Power Controller",
    lastDeploymentAt: "2025-11-01T08:00:00Z",
    status: "active",
  },
  {
    id: "site-008",
    customerId: "cust-004",
    name: "Stuttgart R&D Lab",
    location: "Stuttgart",
    coordinates: { lat: 48.7758, lng: 9.1829 },
    deviceCount: 8,
    status: "active",
  },
  // Texas Renewables Corp
  {
    id: "site-009",
    customerId: "cust-005",
    name: "Austin Solar Farm Alpha",
    location: "Round Rock, TX",
    coordinates: { lat: 30.5083, lng: -97.6789 },
    deviceCount: 35,
    currentFirmwareVersionId: "fwv-301",
    currentFirmwareVersion: "v3.0.0",
    currentFirmwareFamilyName: "INV-4000 Inverter Controller",
    lastDeploymentAt: "2026-01-20T10:00:00Z",
    status: "active",
  },
  {
    id: "site-010",
    customerId: "cust-005",
    name: "Dallas Wind Integration Hub",
    location: "Irving, TX",
    coordinates: { lat: 32.814, lng: -96.9489 },
    deviceCount: 20,
    currentFirmwareVersionId: "fwv-202",
    currentFirmwareVersion: "v2.1.0",
    currentFirmwareFamilyName: "INV-5000 Gateway",
    lastDeploymentAt: "2026-01-10T08:00:00Z",
    status: "active",
  },
];

// ---------------------------------------------------------------------------
// Site Deployments
// ---------------------------------------------------------------------------

export const MOCK_SITE_DEPLOYMENTS: SiteDeployment[] = [
  // site-001: Shanghai HQ — v1.0.0 → v1.2.0
  {
    id: "dep-001",
    siteId: "site-001",
    firmwareVersionId: "fwv-101",
    firmwareVersion: "v1.0.0",
    firmwareFamilyName: "INV-3200 Power Controller",
    deployedBy: "ops.martinez@example.com",
    deployedAt: "2025-08-20T10:00:00Z",
    method: "MANUAL",
    status: "SUCCESS",
    notes: "Initial deployment to Shanghai HQ",
  },
  {
    id: "dep-002",
    siteId: "site-001",
    firmwareVersionId: "fwv-103",
    firmwareVersion: "v1.2.0",
    firmwareFamilyName: "INV-3200 Power Controller",
    deployedBy: "ops.martinez@example.com",
    deployedAt: "2025-11-01T08:00:00Z",
    previousFirmwareVersionId: "fwv-101",
    previousFirmwareVersion: "v1.0.0",
    method: "OTA",
    status: "SUCCESS",
    notes: "Upgrade to signed driver version",
  },
  // site-002: Nanjing — v1.0.0 only
  {
    id: "dep-003",
    siteId: "site-002",
    firmwareVersionId: "fwv-101",
    firmwareVersion: "v1.0.0",
    firmwareFamilyName: "INV-3200 Power Controller",
    deployedBy: "ops.martinez@example.com",
    deployedAt: "2025-08-20T10:00:00Z",
    method: "MANUAL",
    status: "SUCCESS",
  },
  // site-003: Western Sydney — v2.0.0 → v2.1.0
  {
    id: "dep-004",
    siteId: "site-003",
    firmwareVersionId: "fwv-201",
    firmwareVersion: "v2.0.0",
    firmwareFamilyName: "INV-5000 Gateway",
    deployedBy: "ops.martinez@example.com",
    deployedAt: "2025-09-20T09:00:00Z",
    method: "MANUAL",
    status: "SUCCESS",
  },
  {
    id: "dep-005",
    siteId: "site-003",
    firmwareVersionId: "fwv-202",
    firmwareVersion: "v2.1.0",
    firmwareFamilyName: "INV-5000 Gateway",
    deployedBy: "ops.davis@example.com",
    deployedAt: "2026-01-10T08:00:00Z",
    previousFirmwareVersionId: "fwv-201",
    previousFirmwareVersion: "v2.0.0",
    method: "OTA",
    status: "SUCCESS",
    notes: "TLS 1.3 upgrade",
  },
  // site-004: Hunter Valley — v1.2.0
  {
    id: "dep-006",
    siteId: "site-004",
    firmwareVersionId: "fwv-103",
    firmwareVersion: "v1.2.0",
    firmwareFamilyName: "INV-3200 Power Controller",
    deployedBy: "ops.davis@example.com",
    deployedAt: "2025-11-01T08:00:00Z",
    method: "DOWNLOAD_TOKEN",
    status: "SUCCESS",
  },
  // site-005: Brisbane Central — v3.0.0
  {
    id: "dep-007",
    siteId: "site-005",
    firmwareVersionId: "fwv-301",
    firmwareVersion: "v3.0.0",
    firmwareFamilyName: "INV-4000 Inverter Controller",
    deployedBy: "ops.martinez@example.com",
    deployedAt: "2026-01-20T10:00:00Z",
    method: "OTA",
    status: "SUCCESS",
    notes: "Initial inverter controller rollout",
  },
  // site-006: Gold Coast — v2.1.0
  {
    id: "dep-008",
    siteId: "site-006",
    firmwareVersionId: "fwv-202",
    firmwareVersion: "v2.1.0",
    firmwareFamilyName: "INV-5000 Gateway",
    deployedBy: "ops.davis@example.com",
    deployedAt: "2026-01-10T08:00:00Z",
    method: "MANUAL",
    status: "SUCCESS",
  },
  // site-007: Munich Factory — v1.0.0 → v1.2.0
  {
    id: "dep-009",
    siteId: "site-007",
    firmwareVersionId: "fwv-101",
    firmwareVersion: "v1.0.0",
    firmwareFamilyName: "INV-3200 Power Controller",
    deployedBy: "ops.martinez@example.com",
    deployedAt: "2025-08-25T09:00:00Z",
    method: "MANUAL",
    status: "SUCCESS",
  },
  {
    id: "dep-010",
    siteId: "site-007",
    firmwareVersionId: "fwv-103",
    firmwareVersion: "v1.2.0",
    firmwareFamilyName: "INV-3200 Power Controller",
    deployedBy: "ops.davis@example.com",
    deployedAt: "2025-11-01T08:00:00Z",
    previousFirmwareVersionId: "fwv-101",
    previousFirmwareVersion: "v1.0.0",
    method: "OTA",
    status: "SUCCESS",
  },
  // site-009: Austin Solar — v3.0.0
  {
    id: "dep-011",
    siteId: "site-009",
    firmwareVersionId: "fwv-301",
    firmwareVersion: "v3.0.0",
    firmwareFamilyName: "INV-4000 Inverter Controller",
    deployedBy: "ops.martinez@example.com",
    deployedAt: "2026-01-20T10:00:00Z",
    method: "OTA",
    status: "SUCCESS",
  },
  // site-010: Dallas Wind — v2.0.0 → v2.1.0
  {
    id: "dep-012",
    siteId: "site-010",
    firmwareVersionId: "fwv-201",
    firmwareVersion: "v2.0.0",
    firmwareFamilyName: "INV-5000 Gateway",
    deployedBy: "ops.martinez@example.com",
    deployedAt: "2025-09-25T09:00:00Z",
    method: "MANUAL",
    status: "SUCCESS",
  },
  {
    id: "dep-013",
    siteId: "site-010",
    firmwareVersionId: "fwv-202",
    firmwareVersion: "v2.1.0",
    firmwareFamilyName: "INV-5000 Gateway",
    deployedBy: "ops.davis@example.com",
    deployedAt: "2026-01-10T08:00:00Z",
    previousFirmwareVersionId: "fwv-201",
    previousFirmwareVersion: "v2.0.0",
    method: "OTA",
    status: "SUCCESS",
    notes: "Upgrade for TLS 1.3 compliance",
  },
];
