import { FileBox, Package, Scale, Bug } from "lucide-react";
import type {
  Tab,
  SeverityLevel,
  RemediationStatus,
  LicenseCompliance,
  FirmwareOption,
  SBOM,
  SBOMComponent,
  ComponentVulnerability,
} from "./sbom-types";

// =============================================================================
// License Policy
// =============================================================================

export const APPROVED_LICENSES = [
  "Apache-2.0",
  "MIT",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "MPL-2.0",
];
export const RESTRICTED_LICENSES = ["GPL-2.0-only", "GPL-3.0-only", "AGPL-3.0-only"];

export function getLicenseCompliance(license: string): LicenseCompliance {
  if (APPROVED_LICENSES.includes(license)) return "approved";
  if (RESTRICTED_LICENSES.includes(license)) return "restricted";
  return "unknown";
}

// =============================================================================
// Mock Data
// =============================================================================

export const MOCK_FIRMWARE: FirmwareOption[] = [
  { id: "fw-001", name: "SG-INV-5000", version: "2.4.1" },
  { id: "fw-002", name: "SG-INV-5000", version: "2.5.0-rc1" },
  { id: "fw-003", name: "SG-STR-3000", version: "1.8.3" },
  { id: "fw-004", name: "SG-MON-2000", version: "3.1.0" },
  { id: "fw-005", name: "SG-CTL-1000", version: "4.0.2" },
];

export const MOCK_SBOMS: SBOM[] = [
  {
    id: "sbom-001",
    firmwareId: "fw-001",
    firmwareName: "SG-INV-5000",
    firmwareVersion: "2.4.1",
    format: "CycloneDX",
    specVersion: "1.5",
    componentCount: 142,
    vulnerabilityCount: 8,
    licenseCount: 12,
    criticalVulnCount: 2,
    highVulnCount: 3,
    mediumVulnCount: 2,
    lowVulnCount: 1,
    uploadedBy: "Sarah Chen",
    uploadedDate: "2026-03-25T10:30:00Z",
    status: "Complete",
  },
  {
    id: "sbom-002",
    firmwareId: "fw-002",
    firmwareName: "SG-INV-5000",
    firmwareVersion: "2.5.0-rc1",
    format: "SPDX",
    specVersion: "2.3",
    componentCount: 156,
    vulnerabilityCount: 5,
    licenseCount: 14,
    criticalVulnCount: 1,
    highVulnCount: 2,
    mediumVulnCount: 1,
    lowVulnCount: 1,
    uploadedBy: "Sarah Chen",
    uploadedDate: "2026-03-27T14:15:00Z",
    status: "Complete",
  },
  {
    id: "sbom-003",
    firmwareId: "fw-003",
    firmwareName: "SG-STR-3000",
    firmwareVersion: "1.8.3",
    format: "CycloneDX",
    specVersion: "1.5",
    componentCount: 89,
    vulnerabilityCount: 3,
    licenseCount: 8,
    criticalVulnCount: 0,
    highVulnCount: 1,
    mediumVulnCount: 1,
    lowVulnCount: 1,
    uploadedBy: "Mike Rodriguez",
    uploadedDate: "2026-03-20T09:00:00Z",
    status: "Complete",
  },
  {
    id: "sbom-004",
    firmwareId: "fw-004",
    firmwareName: "SG-MON-2000",
    firmwareVersion: "3.1.0",
    format: "CycloneDX",
    specVersion: "1.5",
    componentCount: 0,
    vulnerabilityCount: 0,
    licenseCount: 0,
    criticalVulnCount: 0,
    highVulnCount: 0,
    mediumVulnCount: 0,
    lowVulnCount: 0,
    uploadedBy: "Sarah Chen",
    uploadedDate: "2026-03-28T16:45:00Z",
    status: "Processing",
  },
  {
    id: "sbom-005",
    firmwareId: "fw-005",
    firmwareName: "SG-CTL-1000",
    firmwareVersion: "4.0.2",
    format: "SPDX",
    specVersion: "2.3",
    componentCount: 0,
    vulnerabilityCount: 0,
    licenseCount: 0,
    criticalVulnCount: 0,
    highVulnCount: 0,
    mediumVulnCount: 0,
    lowVulnCount: 0,
    uploadedBy: "Mike Rodriguez",
    uploadedDate: "2026-03-28T17:00:00Z",
    status: "Error",
    errorMessage: "Invalid CycloneDX format: missing required field 'bomFormat'",
  },
];

export const MOCK_COMPONENTS: SBOMComponent[] = [
  {
    id: "comp-001",
    sbomId: "sbom-001",
    name: "openssl",
    version: "3.1.0",
    purl: "pkg:npm/openssl@3.1.0",
    supplier: "OpenSSL Foundation",
    license: "Apache-2.0",
    licenseCompliance: "approved",
    vulnerabilityCount: 2,
    highestSeverity: "Critical",
    scope: "required",
  },
  {
    id: "comp-002",
    sbomId: "sbom-001",
    name: "libcurl",
    version: "8.4.0",
    purl: "pkg:npm/libcurl@8.4.0",
    supplier: "curl Project",
    license: "MIT",
    licenseCompliance: "approved",
    vulnerabilityCount: 1,
    highestSeverity: "High",
    scope: "required",
  },
  {
    id: "comp-003",
    sbomId: "sbom-001",
    name: "zlib",
    version: "1.3.0",
    purl: "pkg:npm/zlib@1.3.0",
    supplier: "Jean-loup Gailly",
    license: "Zlib",
    licenseCompliance: "unknown",
    vulnerabilityCount: 0,
    highestSeverity: null,
    scope: "required",
  },
  {
    id: "comp-004",
    sbomId: "sbom-001",
    name: "busybox",
    version: "1.36.1",
    purl: "pkg:npm/busybox@1.36.1",
    supplier: "BusyBox Team",
    license: "GPL-2.0-only",
    licenseCompliance: "restricted",
    vulnerabilityCount: 1,
    highestSeverity: "Medium",
    scope: "required",
  },
  {
    id: "comp-005",
    sbomId: "sbom-001",
    name: "sqlite",
    version: "3.44.0",
    purl: "pkg:npm/sqlite@3.44.0",
    supplier: "SQLite Consortium",
    license: "blessing",
    licenseCompliance: "unknown",
    vulnerabilityCount: 0,
    highestSeverity: null,
    scope: "optional",
  },
  {
    id: "comp-006",
    sbomId: "sbom-001",
    name: "protobuf",
    version: "25.1.0",
    purl: "pkg:npm/protobuf@25.1.0",
    supplier: "Google LLC",
    license: "BSD-3-Clause",
    licenseCompliance: "approved",
    vulnerabilityCount: 1,
    highestSeverity: "Low",
    scope: "required",
  },
  {
    id: "comp-007",
    sbomId: "sbom-001",
    name: "mosquitto",
    version: "2.0.18",
    purl: "pkg:npm/mosquitto@2.0.18",
    supplier: "Eclipse Foundation",
    license: "EPL-2.0",
    licenseCompliance: "unknown",
    vulnerabilityCount: 0,
    highestSeverity: null,
    scope: "optional",
  },
  {
    id: "comp-008",
    sbomId: "sbom-002",
    name: "openssl",
    version: "3.2.0",
    purl: "pkg:npm/openssl@3.2.0",
    supplier: "OpenSSL Foundation",
    license: "Apache-2.0",
    licenseCompliance: "approved",
    vulnerabilityCount: 0,
    highestSeverity: null,
    scope: "required",
  },
  {
    id: "comp-009",
    sbomId: "sbom-002",
    name: "libcurl",
    version: "8.5.0",
    purl: "pkg:npm/libcurl@8.5.0",
    supplier: "curl Project",
    license: "MIT",
    licenseCompliance: "approved",
    vulnerabilityCount: 1,
    highestSeverity: "High",
    scope: "required",
  },
  {
    id: "comp-010",
    sbomId: "sbom-002",
    name: "libuv",
    version: "1.48.0",
    purl: "pkg:npm/libuv@1.48.0",
    supplier: "libuv contributors",
    license: "MIT",
    licenseCompliance: "approved",
    vulnerabilityCount: 0,
    highestSeverity: null,
    scope: "required",
  },
  {
    id: "comp-011",
    sbomId: "sbom-002",
    name: "jansson",
    version: "2.14",
    purl: "pkg:npm/jansson@2.14",
    supplier: "Petri Lehtinen",
    license: "MIT",
    licenseCompliance: "approved",
    vulnerabilityCount: 0,
    highestSeverity: null,
    scope: "optional",
  },
  {
    id: "comp-012",
    sbomId: "sbom-002",
    name: "linux-kernel",
    version: "6.1.67",
    purl: "pkg:npm/linux-kernel@6.1.67",
    supplier: "Linux Foundation",
    license: "GPL-2.0-only",
    licenseCompliance: "restricted",
    vulnerabilityCount: 2,
    highestSeverity: "Critical",
    scope: "required",
  },
  {
    id: "comp-013",
    sbomId: "sbom-003",
    name: "mbedtls",
    version: "3.5.1",
    purl: "pkg:npm/mbedtls@3.5.1",
    supplier: "Arm Limited",
    license: "Apache-2.0",
    licenseCompliance: "approved",
    vulnerabilityCount: 1,
    highestSeverity: "Medium",
    scope: "required",
  },
  {
    id: "comp-014",
    sbomId: "sbom-003",
    name: "freertos",
    version: "10.6.1",
    purl: "pkg:npm/freertos@10.6.1",
    supplier: "Amazon Web Services",
    license: "MIT",
    licenseCompliance: "approved",
    vulnerabilityCount: 0,
    highestSeverity: null,
    scope: "required",
  },
  {
    id: "comp-015",
    sbomId: "sbom-003",
    name: "lwip",
    version: "2.2.0",
    purl: "pkg:npm/lwip@2.2.0",
    supplier: "lwIP contributors",
    license: "BSD-3-Clause",
    licenseCompliance: "approved",
    vulnerabilityCount: 1,
    highestSeverity: "High",
    scope: "required",
  },
  {
    id: "comp-016",
    sbomId: "sbom-003",
    name: "cjson",
    version: "1.7.16",
    purl: "pkg:npm/cjson@1.7.16",
    supplier: "Dave Gamble",
    license: "MIT",
    licenseCompliance: "approved",
    vulnerabilityCount: 0,
    highestSeverity: null,
    scope: "optional",
  },
  {
    id: "comp-017",
    sbomId: "sbom-002",
    name: "glibc",
    version: "2.38",
    purl: "pkg:npm/glibc@2.38",
    supplier: "GNU Project",
    license: "LGPL-2.1-only",
    licenseCompliance: "unknown",
    vulnerabilityCount: 1,
    highestSeverity: "Medium",
    scope: "required",
  },
  {
    id: "comp-018",
    sbomId: "sbom-001",
    name: "nginx",
    version: "1.25.3",
    purl: "pkg:npm/nginx@1.25.3",
    supplier: "F5 Inc.",
    license: "BSD-2-Clause",
    licenseCompliance: "approved",
    vulnerabilityCount: 1,
    highestSeverity: "High",
    scope: "optional",
  },
];

export const MOCK_VULNERABILITIES: ComponentVulnerability[] = [
  {
    id: "cvuln-001",
    componentId: "comp-001",
    componentName: "openssl",
    componentVersion: "3.1.0",
    sbomId: "sbom-001",
    cveId: "CVE-2026-0001",
    severity: "Critical",
    cvssScore: 9.8,
    description: "Remote code execution via buffer overflow in TLS handshake processing",
    publishedDate: "2026-03-10T00:00:00Z",
    remediationStatus: "In Progress",
    remediationNotes: "Patch scheduled for next firmware release",
    resolvedDate: null,
    affectedVersionRange: ">=3.0.0 <3.1.1",
    fixedVersion: "3.1.1",
  },
  {
    id: "cvuln-002",
    componentId: "comp-001",
    componentName: "openssl",
    componentVersion: "3.1.0",
    sbomId: "sbom-001",
    cveId: "CVE-2026-0045",
    severity: "High",
    cvssScore: 8.1,
    description: "Memory corruption in X.509 certificate verification allows denial of service",
    publishedDate: "2026-02-28T00:00:00Z",
    remediationStatus: "Open",
    remediationNotes: "",
    resolvedDate: null,
    affectedVersionRange: ">=3.0.0 <3.1.2",
    fixedVersion: "3.1.2",
  },
  {
    id: "cvuln-003",
    componentId: "comp-002",
    componentName: "libcurl",
    componentVersion: "8.4.0",
    sbomId: "sbom-001",
    cveId: "CVE-2026-0112",
    severity: "High",
    cvssScore: 7.5,
    description: "HSTS bypass via IDN hostname allows connection downgrade to HTTP",
    publishedDate: "2026-01-15T00:00:00Z",
    remediationStatus: "Open",
    remediationNotes: "",
    resolvedDate: null,
    affectedVersionRange: ">=8.0.0 <8.4.1",
    fixedVersion: "8.4.1",
  },
  {
    id: "cvuln-004",
    componentId: "comp-004",
    componentName: "busybox",
    componentVersion: "1.36.1",
    sbomId: "sbom-001",
    cveId: "CVE-2026-0198",
    severity: "Medium",
    cvssScore: 5.3,
    description: "Stack-based buffer overflow in awk pattern parsing",
    publishedDate: "2026-02-05T00:00:00Z",
    remediationStatus: "Mitigated",
    remediationNotes: "awk utility disabled in production builds; full patch pending upstream fix",
    resolvedDate: null,
    affectedVersionRange: ">=1.35.0 <1.36.2",
    fixedVersion: "1.36.2",
  },
  {
    id: "cvuln-005",
    componentId: "comp-006",
    componentName: "protobuf",
    componentVersion: "25.1.0",
    sbomId: "sbom-001",
    cveId: "CVE-2026-0267",
    severity: "Low",
    cvssScore: 3.1,
    description: "Denial of service via deeply nested message structure",
    publishedDate: "2026-03-01T00:00:00Z",
    remediationStatus: "Resolved",
    remediationNotes: "Updated protobuf max depth configuration",
    resolvedDate: "2026-03-20T14:30:00Z",
    affectedVersionRange: ">=25.0.0 <25.1.1",
    fixedVersion: "25.1.1",
  },
  {
    id: "cvuln-006",
    componentId: "comp-012",
    componentName: "linux-kernel",
    componentVersion: "6.1.67",
    sbomId: "sbom-002",
    cveId: "CVE-2026-0301",
    severity: "Critical",
    cvssScore: 9.1,
    description: "Use-after-free in netfilter subsystem allows local privilege escalation",
    publishedDate: "2026-03-15T00:00:00Z",
    remediationStatus: "Open",
    remediationNotes: "",
    resolvedDate: null,
    affectedVersionRange: ">=6.1.0 <6.1.70",
    fixedVersion: "6.1.70",
  },
  {
    id: "cvuln-007",
    componentId: "comp-012",
    componentName: "linux-kernel",
    componentVersion: "6.1.67",
    sbomId: "sbom-002",
    cveId: "CVE-2026-0315",
    severity: "High",
    cvssScore: 7.8,
    description: "Race condition in io_uring allows arbitrary write to kernel memory",
    publishedDate: "2026-03-18T00:00:00Z",
    remediationStatus: "Open",
    remediationNotes: "",
    resolvedDate: null,
    affectedVersionRange: ">=6.1.0 <6.1.69",
    fixedVersion: "6.1.69",
  },
  {
    id: "cvuln-008",
    componentId: "comp-009",
    componentName: "libcurl",
    componentVersion: "8.5.0",
    sbomId: "sbom-002",
    cveId: "CVE-2026-0389",
    severity: "High",
    cvssScore: 7.2,
    description: "Cookie injection via HTTP redirect allows session hijacking",
    publishedDate: "2026-03-20T00:00:00Z",
    remediationStatus: "In Progress",
    remediationNotes: "Upgrade to 8.5.1 included in next build",
    resolvedDate: null,
    affectedVersionRange: ">=8.5.0 <8.5.1",
    fixedVersion: "8.5.1",
  },
  {
    id: "cvuln-009",
    componentId: "comp-017",
    componentName: "glibc",
    componentVersion: "2.38",
    sbomId: "sbom-002",
    cveId: "CVE-2026-0421",
    severity: "Medium",
    cvssScore: 5.9,
    description: "Buffer overflow in iconv conversion for certain character sets",
    publishedDate: "2026-03-22T00:00:00Z",
    remediationStatus: "Open",
    remediationNotes: "",
    resolvedDate: null,
    affectedVersionRange: ">=2.37 <2.39",
    fixedVersion: "2.39",
  },
  {
    id: "cvuln-010",
    componentId: "comp-013",
    componentName: "mbedtls",
    componentVersion: "3.5.1",
    sbomId: "sbom-003",
    cveId: "CVE-2026-0455",
    severity: "Medium",
    cvssScore: 5.5,
    description: "Timing side-channel in RSA private key operations",
    publishedDate: "2026-03-08T00:00:00Z",
    remediationStatus: "In Progress",
    remediationNotes: "Applying constant-time implementation patch",
    resolvedDate: null,
    affectedVersionRange: ">=3.5.0 <3.5.2",
    fixedVersion: "3.5.2",
  },
  {
    id: "cvuln-011",
    componentId: "comp-015",
    componentName: "lwip",
    componentVersion: "2.2.0",
    sbomId: "sbom-003",
    cveId: "CVE-2026-0478",
    severity: "High",
    cvssScore: 7.4,
    description: "TCP sequence number prediction allows spoofed connection injection",
    publishedDate: "2026-03-12T00:00:00Z",
    remediationStatus: "Open",
    remediationNotes: "",
    resolvedDate: null,
    affectedVersionRange: ">=2.1.0 <2.2.1",
    fixedVersion: "2.2.1",
  },
  {
    id: "cvuln-012",
    componentId: "comp-018",
    componentName: "nginx",
    componentVersion: "1.25.3",
    sbomId: "sbom-001",
    cveId: "CVE-2026-0512",
    severity: "High",
    cvssScore: 7.0,
    description: "HTTP/2 rapid reset attack allows denial of service",
    publishedDate: "2026-03-05T00:00:00Z",
    remediationStatus: "Resolved",
    remediationNotes: "Upgraded to nginx 1.25.4 with rate limiting",
    resolvedDate: "2026-03-22T10:00:00Z",
    affectedVersionRange: ">=1.25.0 <1.25.4",
    fixedVersion: "1.25.4",
  },
];

// =============================================================================
// Severity helpers
// =============================================================================

export const SEVERITY_CONFIG: Record<SeverityLevel, { color: string; bg: string; border: string }> =
  {
    Critical: { color: "text-red-700", bg: "bg-red-50", border: "border-red-200" },
    High: { color: "text-orange-700", bg: "bg-orange-50", border: "border-orange-200" },
    Medium: { color: "text-amber-700", bg: "bg-amber-50", border: "border-amber-200" },
    Low: { color: "text-green-700", bg: "bg-green-50", border: "border-green-200" },
  };

export const REMEDIATION_CONFIG: Record<RemediationStatus, { color: string; bg: string }> = {
  Open: { color: "text-red-700", bg: "bg-red-50" },
  "In Progress": { color: "text-amber-700", bg: "bg-amber-50" },
  Mitigated: { color: "text-blue-700", bg: "bg-blue-50" },
  Resolved: { color: "text-green-700", bg: "bg-green-50" },
};

export const LICENSE_COMPLIANCE_CONFIG: Record<
  LicenseCompliance,
  { label: string; color: string; bg: string }
> = {
  approved: { label: "Approved", color: "text-green-700", bg: "bg-green-50" },
  restricted: { label: "Restricted", color: "text-red-700", bg: "bg-red-50" },
  unknown: { label: "Unknown", color: "text-gray-600", bg: "bg-gray-100" },
};

// =============================================================================
// Page Tabs
// =============================================================================

export const TABS: { id: Tab; label: string; icon: React.ComponentType<{ className?: string }> }[] =
  [
    { id: "management", label: "SBOM Management", icon: FileBox },
    { id: "components", label: "Component Explorer", icon: Package },
    { id: "cve-dashboard", label: "CVE Dashboard", icon: Bug },
    { id: "license-compliance", label: "License Compliance", icon: Scale },
  ];

// =============================================================================
// Pagination
// =============================================================================

export const PAGE_SIZE = 25;

export const PIE_COLORS = [
  "#2563eb",
  "#8b5cf6",
  "#06b6d4",
  "#10b981",
  "#f59e0b",
  "#ef4444",
  "#6b7280",
];
